@url = https://supreme-system-wvr44p4r76c96pv-3000.app.github.dev

GET {{url}}/api/v1/generos
###
GET {{url}}/api/v1/generos/1

###
POST {{url}}/api/v1/generos
Content-Type: application/json

{
    "id" : 10,
    "nome" : "Biografia"
}